# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/kubernetes-incubator/external-storage"

[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.0-beta.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.0-beta.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.0-beta.1"

[[constraint]]
  name = "k8s.io/kubernetes"
  revision = "48b7bb56341914b85c76700becadc02b8009d9a0"

